apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server
data:
  # property-like keys; each key maps to a simple value
  CONFIG_SERVER_URL: "http://config-server:8888"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=795159a5-bc66-4021-87d2-b784e05354f0;IngestionEndpoint=https://eastus2-3.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus2.livediagnostics.monitor.azure.com/;ApplicationId=e34748e1-97df-4bde-87f9-7b019515be07"